using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class PayoutCalculation : MonoBehaviour
{
    [SerializeField]
    private int x_Distance;
    [SerializeField]
    private int y_Distance;

    [SerializeField]
    private Transform LineContainer;
    [SerializeField]
    private GameObject Line_Prefab;

    [SerializeField]
    private Vector2 InitialLinePosition = new Vector2(-315, 100);

    [SerializeField] internal List<int> LineList;
    [SerializeField] private List<GameObject> LineObjetcs;
    [SerializeField] internal List<int> DontDestroyLines = new List<int>();


    //generate lines at runtime accordingly
    internal void GeneratePayoutLinesBackend(int index = -1, bool DestroyFirst = true)
    {

        if (DestroyFirst)
            ResetStaticLine();

        if (index >= 0)
        {
            LineObjetcs[index].SetActive(true);
            print("line object name"+LineObjetcs[index].name);
            return;
        }
        DontDestroyLines.Clear();
    }
    //delete the line generated by button hover
    internal void ResetStaticLine()
    {
        for (int i = 0; i < LineObjetcs.Count; i++)
        {
            if (DontDestroyLines.Contains(i))
                continue;
            else
                LineObjetcs[i].SetActive(false);
        }
    }
}
